server:
  port: 8088
  servlet:
    context-path: /beFine

spring:
  jackson:
    serialization:
      indent-output: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/beFineDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Normandia1$
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dll-auto: update
